### ISSUE TITLE
[UPDATE] 1.12

### ISSUE THREAD

**Issue by CormacZ** [astei/lazydfu#34]

**Comment by astei** [comment]
Minecraft 1.12 doesn't have DFU, or for that matter, official Fabric support

**Comment by CormacZ** [comment]
> Minecraft 1.12 doesn't have DFU, or for that matter, official Fabric support

Oops, I mean 1.20 💀. I'm used to play on 1.12 too much lol

**Comment by astei** [comment]
I'm not updating the mod for 1.20 since Mojang optimized DFU load times significantly enough that this mod likely won't make a dent except for the very lowest-end systems. Until I see credible evidence otherwise, an update is unlikely.

You're free to try the latest build and see if it works. I don't think the relevant logic has changed all that much.
